config/routes.rb
Rails.application.routes.draw do

  get '/articles' => 'articles#index', as: :articles
  get '/articles/:tag/:search_term' => 'articles#show', as: :article

  resources :tests
  root 'sessions#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

end

app/models/bing_fetcher.rb
class BingFetcher
  attr_reader :bing_image
  def initialize
    @bing_image = Bing.new(ENV['PRIMARY_ACCOUNT_KEY'], 1, 'Image')
  end

  def image_search(image)
    unless @bing_image.search(image).nil?
      unless @bing_image.search(image)[0].nil?
        unless @bing_image.search(image)[0][:Image][0].nil?
    @bing_image.search(image)[0][:Image][0][:Thumbnail][:MediaUrl]
        end
      end
    end
  end
end

app/models/npr_fetcher.rb
class NprFetcher

  def initialize
    @conn = Faraday.new(:url => 'http://api.npr.org') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP  end
    end

  def npr_news(searchterm)
    response = @conn.get do |req|
      # req.url "/query?dateType=story&searchTerm=#{searchterm}&output=MediaRSS&searchType=fullContent&output=JSON&apiKey=#{ENV['NPR_API_KEY']}&sort=relevance"
      # req.url "/query?searchinput=#{searchterm}&output=MediaRSS&searchType=fullContent&output=JSON&apiKey=#{ENV['NPR_API_KEY']}&sort=relevance"
      req.url "/query?searchTerm=#{searchterm}&dateType=story&dateID=365&output=JSON&apiKey=#{ENV['NPR_API_KEY']}&sort=relevance"
      req.headers['content-type'] = 'application/json'
    end
    @returnedsearch= JSON.parse(response.body)
  end

  def titles_urls(searchterm)
    Rails.cache.fetch("reposnprshow/#{searchterm}", expires_in:1.hours) do
    @new = NprFetcher.new
    @search = @new.npr_news(searchterm)
    unless @search.nil?
      unless @search['list']['story'].nil?
      @search['list']['story'][0..9].map do |child|


      if child['thumbnail'].present?
        if child['thumbnail']['large'].present?
          img_val = child['thumbnail']['large']['$text']
        else
          img_val = BingFetcher.new.image_search(child['title']['$text'])
        end
      else
        img_val = BingFetcher.new.image_search(child['title']['$text'])
      end

      if img_val.nil?
        img_val = '4non-default.jpg'
      end

      if child["teaser"].present?
        teaser_val = child["teaser"]["$text"]
      end
      # if child['title'].present?
      #   title = child['title']['$text']
      # end

      # unless BingFetcher.new.image_search(child['title']['$text']).nil?
        # img = BingFetcher.new.image_search(child['title']['$text'])
      # end


      {title: child['title']['$text'], url: child['link'][0]['$text'],
        img: img_val, des: teaser_val}
    end
  end
  end
  end
  end


  def title_url(searchterm)
    Rails.cache.fetch("reposnpr/#{searchterm}", expires_in:1.hours) do
    @new = NprFetcher.new
    @search = @new.npr_news(searchterm)
    unless @search.nil?
      unless @search['list']['story'].nil?

        if @search['list']['story'][0]['thumbnail'].present?
          img_val = @search['list']['story'][0]['thumbnail']['large']['$text']
        else
          img_val = BingFetcher.new.image_search(@search['list']['story'][0]['title']['$text'])
        end

        if img_val.nil?
          img_val = "4non-default.jpg"
        end

        if @search['list']['story'][0]["teaser"].present?
          teaser_val = @search['list']['story'][0]["teaser"]["$text"]
        end

          {title: @search['list']['story'][0]['title']['$text'],
            url: @search['list']['story'][0]['link'][-1]['$text'],
            img: img_val, des: teaser_val
            }

        end
      end
      end
    end

  def npr_image(image)
    @npr_image = BingFetcher.new
    @article_image = @image.image_search(image)

    # url: @search['list']['story'][0]['link'][-1]['$text']
  end


end
end

app/models/reddit_fetcher.rb
class RedditFetcher
def initialize
  @conn = Faraday.new(:url => 'http://www.reddit.com') do |faraday|
    faraday.request  :url_encoded             # form-encode POST params
    faraday.response :logger                  # log requests to STDOUT
    faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
  end

  def reddit_news(searchterm)
    @searchterm = searchterm

    response = @conn.get do |req|
      req.url "/r/news/search.json?q=#{@searchterm}&restrict_sr=on&sort=relevance&t=week"
      req.headers['content-type'] = 'application/json'
    end
    @returnedsearch= JSON.parse(response.body)
  end

  def titles_urls(searchterm)
    @new = RedditFetcher.new
    @new.reddit_news(searchterm)['data']['children'].map do |child|
      {title: child['data']['title'], url: child['data']['url']}
    end
  end

end
end


 #reddit_news['data']['children'].map{|child| child['data']['title']

app/models/twitter_fetcher.rb
class TwitterFetcher

  attr_reader :client

  def initialize
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.consumer_key
      config.consumer_secret     = Rails.application.secrets.consumer_secret
      config.access_token        = Rails.application.secrets.access_token
      config.access_token_secret = Rails.application.secrets.access_token_secret
    end
  end

  def trends(id, options={})
    options[:id] = id
    response = get("/1.1/trends/place.json", options)
    collection_from_array(Twitter::Trend, response[:body].first[:trends])[0..8]
  end

  def human(woeid)
    Rails.cache.fetch("twittertrends/#{woeid}", expires_in:5.minutes) do
    @client.trends(woeid).map do |trend|
      {tag: trend[:name], search_term: trend[:name].underscore.humanize.gsub("#", "") }
    end
    end
  end



end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
     @current_user ||= User.find_by(uid: session[:user_id])
  end
  helper_method :current_user


  def authenticate
    unless current_user
      redirect_to root_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate

  def index
    @nprfetcher = NprFetcher.new
    @tfetcher = TwitterFetcher.new
  if params[:param].nil?
    @woeid = 23424977
  else
    @woeid = params[:param]
  end
    @faketweets = [{:tag=>"#WhatDoesHappinessMean", :search_term=>"what does happiness mean"},
      {:tag=>"#DitchYourDateIn5Words", :search_term=>"ditch your date in5 words"},
      {:tag=>"#NBABands", :search_term=>"nba bands"},
      {:tag=>"#WonderfulNewsInFourWords", :search_term=>"wonderful news in four words"},
      {:tag=>"#AgDay2015", :search_term=>"ag day2015"},
      {:tag=>"Moynihan", :search_term=>"Moynihan"},
      {:tag=>"1 Gotta Go", :search_term=>"1 gotta go"},
      {:tag=>"Tunisia", :search_term=>"Tunisia"},
      {:tag=>"Jim Boeheim", :search_term=>"Jim boeheim"},
      {:tag=>"Bradley Fletcher", :search_term=>"Bradley fletcher"}]
  end

  def show
    @nprfetcher = NprFetcher.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   def new
     if current_user
       redirect_to articles_path
     end
   end

   def create
      uid = env['omniauth.auth']['uid']
      session[:user_id] = uid
      user = User.find_or_create_by(uid: uid)
      user.update_attributes(name: env['omniauth.auth']['info']['name'], email: env['omniauth.auth']['info']['email'])
      redirect_to '/articles#index'
   end

   def destroy
      session.clear
      redirect_to root_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="art-hero">

  <div class="grid">
  <%= image_tag "whats-going-on.png", class:"art-logo", alt:"Whats Going on?!" %>

      <% if current_user %>
      <%= link_to 'Logout', signout_path, class: 'btn btn-success art-logout' %>
      <% end %>

      <p class="tag">
        <% if params[:param] == "1" %>
          <%= link_to 'World', '/articles?param=1', class:"color active" %> /
        <% else %>
          <%= link_to 'World', '/articles?param=1', class:"color" %> /
        <% end %>

        <% if params[:param] == "23424977" %>
          <%= link_to 'United States', '/articles?param=23424977', class:"color active" %> /
        <% elsif params[:param] == nil %>
          <%= link_to 'United States', '/articles?param=23424977', class:"color active" %> /
        <% else %>
          <%= link_to 'United States', '/articles?param=23424977', class:"color" %> /
        <% end %>

        <% if params[:param] == "2391279" %>
          <%= link_to 'Denver, CO', '/articles?param=2391279', class:"color active" %>
        <% else %>
          <%= link_to 'Denver, CO', '/articles?param=2391279', class:"color" %>
        <% end %>
    </p>
</div>

</div>
<div class="container">

<% @tfetcher.human(@woeid)[0..8].each do |tweet| %>
<%# @faketweets.each do |tweet| %>
  <% unless @nprfetcher.title_url(tweet[:search_term]).nil? %>
    <div class="col-4-12">
      <div class="big-box">
        <p class="hashtag"><%= image_tag "twitter-icon.png", class:"twit" %> <%= "#{tweet[:tag]}" %></p>

        <% @cat = @nprfetcher.title_url(tweet[:search_term])%>

        <div class="small-img-box">
          <% unless @cat[:img].nil? %>
            <%= link_to image_tag(@cat[:img], class: "img-sm-adj"), @cat[:url], :target => "_blank" %>
          <% end %>
        </div>

        <div class="small-box-txt">
          <h1><%= link_to @cat[:title], @cat[:url], class:"title" %></h1>
          <!-- <p class="tbox">Abunch of text that gets pulled in from cool things that we did as a group. This text will
          disapear here in a minute</p> -->
          <div class="more-articles"
          <p class="more"><%= link_to article_path(tag: tweet[:tag], search_term: tweet[:search_term]) do %>
             <%= image_tag('eye-con.png', class:"twit-sesh") %> See More Articles
          <% end %></p>
          </div>
        </div>

        <div class="small-box"></div>

        <div class="img-box">
          <% unless @cat[:img].nil? %>
            <%= link_to image_tag(@cat[:img], class: "img-adj"), @cat[:url], :target => "_blank" %>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
<% end %>
</div>


<footer>
  <div class="container">
    <hr>
    <ul>

    <div class="col-2-12">
      <%= image_tag "whats-going-on.png", class:"foot-logo", alt:"Whats Going on?!" %>
    </div>
      <li class="col-2.5-12 f-right">&copy; <%= Time.now.year %> WHAT'S GOING ON?!</li>
    </ul>
  </div>
</footer>

app/views/articles/show.html.erb
<div class="art-hero">

  <div class="grid">
  <%= link_to (image_tag "whats-going-on.png", class:"art-logo", alt:"Whats Going on?!"), articles_path %>

      <% if current_user %>
      <%= link_to 'Logout', signout_path, class: 'btn btn-success art-logout' %>
      <% end %>
      <p class="tag">
        <%= image_tag "twitter-icon.png", class:"twit" %> <%= params['tag'] %>
      </p>
    </div>
</div>

<div class="container">

<% @nprfetcher.titles_urls(params['search_term']).map do |cat| %>
<div class="col-6-12">
  <div class="big-box-show">

    <div class="col-6-12">
      <%= link_to cat[:title], cat[:url], class:"title-show", :target => "_blank"  %>
      <div class = "img-box">
        <% unless cat[:img].nil? %>
        <%= image_tag(cat[:img], class: "img-adj-show") %>
        <% end %>
      </div>
    </div>

    <div class="col-6-12">
      <div class = 'show-small-box-txt'>
        <%= truncate cat[:des].html_safe, length: 200 %>
      </div>
      <div class="show-small-box"></div>
    </div>

  </div>
</div>
<% end %>

</div>

<footer>
  <div class="container">
    <hr>
    <ul>
    <div class="col-2-12">
      <%= image_tag "whats-going-on.png", class:"foot-logo", alt:"Whats Going on?!" %>
    </div>
      <li class="col-2.5-12 f-right">&copy; <%= Time.now.year %> WHAT'S GOING ON?!</li>
    </ul>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What's Going On?!</title>
  <%= favicon_link_tag 'wgo-fav.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300italic,300,400italic,500,500italic,700' rel='stylesheet' type='text/css'>
</head>
  <body>
  <%= yield %>
  </body>
</html>